name: Bug
description: Relatar um problema reproduzível
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Problema
      description: Descreva o que aconteceu e o que deveria acontecer.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Sistema
      options: [macOS, Windows]
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versão
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Como reproduzir
    validations:
      required: true
